Fourth Task using Numpy: Indexing and Slicing 

In [2]:
import numpy as np

In [3]:
arr = np.array([
 [10, 20, 30, 40],
 [50, 60, 70, 80],
 [90, 100, 110, 120]
])

In [4]:
arr


array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [5]:
print("Extract Second Row:\n", arr[1])

Extract Second Row:
 [50 60 70 80]


In [6]:
print("Extract first two rows and second two columns:\n", arr[:2, 2:])

Extract first two rows and second two columns:
 [[30 40]
 [70 80]]


In [7]:
print(f"Extract the last column:\n{arr[:,-1]}")

Extract the last column:
[ 40  80 120]


In [8]:
arr[1] = [1,2,3,4]

In [9]:
print("After replacing Middle Row:\n", arr)

After replacing Middle Row:
 [[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
