Second task of Numpy: Array Creation and Data types

In [2]:
import numpy as np

In [3]:
array_1d = np.arange(1,10)

In [4]:
print("Created a 1D array:\n", array_1d)

Created a 1D array:
 [1 2 3 4 5 6 7 8 9]


creating a 2D array

In [7]:
array_2d = np.arange(0,9).reshape(3,3)

In [8]:
print("Created a 2D array:\n", array_2d)

Created a 2D array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print("1D Array details: ")
print("Dimentions:", array_1d.ndim)
print("Shape:",array_1d.shape)
print("Size:", array_1d.size)
print("Data Type:", array_1d.dtype)
print("Size of each element:", array_1d.itemsize)

1D Array details: 
Dimentions: 1
Shape: (9,)
Size: 9
Data Type: int64
Size of each element: 8


In [23]:
print("2D Array details: ")
print("Dimentions:", array_2d.ndim)
print("Shape:",array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)
print("Size of each element:", array_2d.itemsize)

2D Array details: 
Dimentions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Size of each element: 8


In [24]:
flo_array = np.array([
 [1.2, 4.0,3.2],
 [2.0, 0.1, 5.0],
 [4.4,5.8,6.1]
])

In [25]:
print(f"Float Array:\n{flo_array}")

Float Array:
[[1.2 4.  3.2]
 [2.  0.1 5. ]
 [4.4 5.8 6.1]]


In [26]:
flo_array.dtype

dtype('float64')

Now converting a float array into an integar array

In [22]:
int_array = flo_array.astype(int)

In [15]:
print(f"Integar array:\n{int_array}")

Integar array:
[[1 4 3]
 [2 0 5]
 [4 5 6]]


In [16]:
int_array.dtype

dtype('int64')