Seventh taks of Numpy:Using  Fatten, Ravel and Reshape

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,13)

In [3]:
arr.shape

(12,)

In [4]:
arr1 = arr.reshape(3,4)

In [5]:
arr1.shape

(3, 4)

In [6]:
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Fatten and Ravel on a Array

In [7]:
arr2 = np.array([
 [3,6,8,9,5],
 [2,7,4,1,0]
])

In [8]:
print(arr2)



[[3 6 8 9 5]
 [2 7 4 1 0]]


In [9]:
ravel_arr = arr2.ravel()

In [10]:
ravel_arr

array([3, 6, 8, 9, 5, 2, 7, 4, 1, 0])

In [11]:
ravel_arr[0] = 100

In [12]:
ravel_arr

array([100,   6,   8,   9,   5,   2,   7,   4,   1,   0])

In [13]:
arr2

array([[100,   6,   8,   9,   5],
       [  2,   7,   4,   1,   0]])

Ravel converts any arrays into a 1D array and what we modify in it, it modifies in the original array too and makes a  view of it.....

In [14]:
flatten_arr = arr2.flatten()

In [15]:
print(flatten_arr)

[100   6   8   9   5   2   7   4   1   0]


In [16]:
flatten_arr[2] = 60

In [17]:
flatten_arr

array([100,   6,  60,   9,   5,   2,   7,   4,   1,   0])

In [18]:
arr2

array([[100,   6,   8,   9,   5],
       [  2,   7,   4,   1,   0]])

Flatten also converts any arrays into 1D array but what we modify in it, it makes a copy of the original array changes nothin init....


The Given Array

In [19]:
arr = np.arange(1,10).reshape(3,3)

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
flat_arr = arr.flatten()

In [22]:
flat_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
rave_arr = arr.ravel()

In [24]:
rave_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])