Sixth Task of Numpy: Broadcasting 

In [1]:
import numpy as np

In [2]:
arr = np.array([
 [3,5,9],
 [2,4,6],
 [1,7,8]
])

In [3]:
arr.shape

(3, 3)

Adding a scaler Value that is 10 here

In [4]:
add_num = arr + 10

In [5]:
add_num.shape

(3, 3)

In [6]:
add_num 

array([[13, 15, 19],
       [12, 14, 16],
       [11, 17, 18]])

Row Broadcasting 

In [7]:
row = np.array([1,2,3])

In [8]:
broad_row = arr + row

In [9]:
broad_row.shape

(3, 3)

In [10]:
broad_row

array([[ 4,  7, 12],
       [ 3,  6,  9],
       [ 2,  9, 11]])

Column Broadcasting

In [11]:
co_vec = np.array([
 [1],
 [2],
 [3]
])

In [12]:
broad_colum = arr + co_vec

In [13]:
broad_colum.shape

(3, 3)

In [14]:
broad_colum

array([[ 4,  6, 10],
       [ 4,  6,  8],
       [ 4, 10, 11]])