Third task of Numpy: Working with the Numpy Built-in functions 

In [1]:
import numpy as np

A zeros matxix

In [2]:
zero_array = np.zeros((4,4))

In [3]:
print("A Zeros Matrix:\n", zero_array)

A Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


A ones Matrix

In [4]:
one_array = np.ones((3,2))

In [5]:
print(f"A ones matrix:\n{one_array}")

A ones matrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Identify 

In [6]:
ident_array = np.eye(5,5)

In [7]:
print(f"Identify Martxix:\n{ident_array}")

Identify Martxix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Seven Filled 

In [8]:
seven_array = np.full((3,3), 7)

In [9]:
print("The Seven filled Matrix:\n", seven_array)

The Seven filled Matrix:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Random 3x4 Matrix

In [10]:
rand_array = np.random.randint(10,99, size=(3,4))

In [11]:
print(f"A 3x4 matrix:\n{rand_array}")

A 3x4 matrix:
[[48 11 10 85]
 [65 96 82 12]
 [89 32 18 14]]


5 Step Matrix

In [12]:
range_array = np.arange(5, 50, 5).reshape(3,3)

In [13]:
print("Range Matrix:\n", range_array)

Range Matrix:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
